### PR TITLE
GPII-1855 - Upgrade to Fedora 24

### PR DESCRIPTION
**Pull request by gtirloni**
To test, retrieve this PR and run:

```
vagrant up
grunt tests
```

### CODE REVIEW

**Comment by avtar** [comment]
Worked for me :+1:

**Comment by javihernandez** [comment]
Worked fine, although I had to destroy the old box and perform a 'vagrant up' from scratch.

**Comment by javihernandez** [comment]
@gtirloni 

while testing this a bit more, I found out that chrome can't be used. Is that happening to you too?

**Comment by gtirloni** [comment]
Try to disable 3D acceleration by adding this to your Vagrantfile:

```
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
  end
```

What's your host OS and VirtualBox version? Maybe we should consider disabling 3D acceleration by default for this box.

**Comment by javihernandez** [comment]
> Try to disable 3D acceleration by adding this to your Vagrantfile:

Yup, that solves the issue.

> What's your host OS and VirtualBox version? Maybe we should consider disabling 3D acceleration by default for this box.

I'm on openSUSE Tumbleweed, VirtualBox 5.0.18 from openSUSE's Virtualization repo. And yes, since we're already considering disabling 3d acceleration, go for it! Can you update this pr and the universal's?

**Comment by gtirloni** [comment]
After extensive testing, it was determined that 3D support for Linux guests on VirtualBox is provided by the vendor in a "[best effort](https://www.virtualbox.org/wiki/X11Guest3D)" basis and cannot be relied upon.

Updated this PR to disable 3D acceleration in accordance with [GPII-1854](https://issues.gpii.net/browse/GPII-1854).

**Pull request merged**
