### PR TITLE
GPII-2060 - Bind mount node_modules in /var/tmp

### PR DESCRIPTION
**Pull request by gtirloni**
As discussed in https://github.com/idi-ops/ansible-nodejs/pull/35

### CODE REVIEW

**Comment by avtar** [comment]
While attempting to test the latest Fedora VM using Vagrant 1.9.1 and VirtualBox 5.1.10 I got the following symlink related error:
```
npm ERR! path ../acorn/bin/acorn
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/home/vagrant/sync/node_modules/.bin/acorn'
```
Adding @gtirloni's changes from this PR results in ``vagrant up`` finishing the provisioning process as expected.

**Comment by gtirloni** [comment]
@GPII/core-architecture-committers any concerns merging this?

Hopefully all this logic can be migrated to @amatas' vagrant-gpii-qi plugin where it can be updated centrally, but for now we require this workaround to live in the local Vagrantfile so people on Windows/OSX don't have issues with symlinks (which isn't supported by VirtualBox Shared Folders, thus this workaround).

**Comment by gtirloni** [comment]
ok to test

**Comment by gtirloni** [comment]
ok to test

**Comment by gtirloni** [comment]
ok to test

**Comment by gtirloni** [comment]
ok to test

**Comment by gtirloni** [comment]
Fix proposed in November 2016 continues to work. Now it's not a good to have but a necessary thing due to [GPII-2835](https://issues.gpii.net/browse/GPII-2835).

**Comment by amatas** [comment]
This PR looks good to me, in the sense that it will work in a Vagrant environment. Also, the change to the Vagrant-CI yaml definition is easy:

i.e:
```
- mkdir -p /var/tmp/gpii_linux/node_modules /home/vagrant/sync/node_modules
- chown vagrant:vagrant -R /var/tmp/gpii_linux/node_modules /home/vagrant/sync/node_modules
- mount -o bind /var/tmp/gpii_linux/node_modules  /home/vagrant/sync/node_modules
```

**Pull request merged**
