### PR TITLE
GPII-1318: Attempt to update linux repo to node 4.2.x

### PR DESCRIPTION
**Pull request by amb26**
Currently non-building due to failure to compile gsettings addon.

### CODE REVIEW

**Comment by amb26** [comment]
@javihernandez - I've JIRAed the Gsettings build failure at https://issues.gpii.net/browse/GPII-1526 - perhaps you could take a look - cheers!
This branch should be deployed together with https://github.com/GPII/universal/pull/425

**Comment by amb26** [comment]
Linux has become the DIRTY MAN OF EUROPE! : P

**Comment by javihernandez** [comment]
Hey @amb26, 

I *think* I saw this coming a year ago or so, so thanks for bringing it. Will take a look at it ASAP.
GOD SAVE THE EMPIRE!!! :P

**Comment by javihernandez** [comment]
@amb26, 

I've told @klown that we best start using nan to keep backwards compatibility with older versions of node. Anything against it? Is there any reason for stop supporting old versions of node and start focusing on 4.* (so we can get rid of nan?)

**Comment by colinbdclark** [comment]
I think in general if we've got any C++ code that depends on Node APIs, we should always use nan. I look forward to dropping older versions of Node and only supporting 4.x, but even then we should use nan so we are somewhat more shielded from changes in V8. All the documentation I've read suggests that nan is pretty much a requirement for anyone writing C++ modules for Node at this point.

**Comment by javihernandez** [comment]
@colinbdclark, 

exactly, I think nan has become the de facto standard for writing native modules, but I was asking @amb26 in case he had anything against it. So far, I've started moving our base code to use nan but it's still unfinished, I'm hoping to get something by the next week.

**Comment by amb26** [comment]
Of course I've got nothing against NAN, do you think I'm completely insane? :)

**Comment by gtirloni** [comment]
Just a heads up 4.3.0 is out and contains behavior changes in HTTP parsing.

https://nodejs.org/en/blog/vulnerability/february-2016-security-releases/

**Comment by gtirloni** [comment]
4wbkvxm_700wa_0

**Pull request merged**
