### PR TITLE
GPII-2713 - Upgrade to Fedora 27

### PR DESCRIPTION
**Pull request by gtirloni**
Includes Chrome 62 and Firefox57

### CODE REVIEW

**Comment by gtirloni** [comment]
ok to test

**Comment by gtirloni** [comment]
The F27 box was updated to include Chrome 63. All tests continue to pass. I recommend merging this PR unless there are any concerns.

**Comment by gtirloni** [comment]
ok to test

**Comment by javihernandez** [comment]
> CI job passed: https://ci.gpii.net/job/linux-tests/130/

Personally, I wouldn't count this (https://ci.gpii.net/job/linux-acceptance-tests/130/console) as "success". This problem is due to node 8, see https://issues.gpii.net/browse/GPII-2795 and https://issues.gpii.net/browse/GPII-2673 for more information. I haven't had time to deep dive into this yet, so I'd say that for the time being, we need to stick to node 6 series until we solve our problems with node 8.

**Comment by gtirloni** [comment]
Understood. However, this is not a problem for this PR or Fedora 27. Node.js (and npm) are installed according to the repository's specification.

https://github.com/GPII/linux/blob/master/provisioning/vars.yml

**Comment by gtirloni** [comment]
ok to test

**Comment by javihernandez** [comment]
Thanks @gtirloni!

**Pull request merged**
